name: github pages

on:
  push:
    branches: [ master ]
  pull_request:
    paths: 
      - .github/workflows/github_pages.yml

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '14.x'

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      # Workaround for https://github.blog/2021-09-01-improving-git-protocol-security-github/
      - run: git config --global url."https://github.com/".insteadOf git://github.com/
      - run: npm ci
      - run: NODE_ENV=development npm run build:prod

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
